spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/kangxin?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.drawnblue.entity
server:
  port: 8011
